apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: frontend-secret
    literals:
      - BACKEND_URL="http://backend-app:8000"
  - name: backend-secret
    literals:
      - REDIS_URL="redis://abhra:1234@redis-service:6379"

resources:
  - backend-resources.yaml
  - frontend-resources.yaml
  - redis-resources.yaml

patches:
  - path: patch-frontend.yaml
  - path: patch-backend.yaml