apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v1

resources:
  - backend-resources.yaml
  - frontend-resources.yaml

images:
  - name: abhradippaul/nodejs-frontend-devops
    newTag: v1
  - name: abhradippaul/nodejs-backend-devops
    newTag: v1
