apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-resources.yaml
  - frontend-resources.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: frontend-secret
    literals:
      - BACKEND_URL="http://backend-app:8000"
  - name: backend-secret
    literals:
      - FRONTEND_URL="http://frontend-app"

patches:
  - path: patch-frontend.yaml
  - path: patch-backend.yaml