name: Node CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths: ["frontend/**", "backend/**", ".github/**"]
  pull_request:
    branches: ["main"]
    paths: ["frontend/**", "backend/**", ".github/**"]

permissions:
  contents: write

jobs:
  check-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"

      - name: npm install, lint and build for frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: npm install, lint and build for backend
        working-directory: backend
        run: |
          npm ci
          npm run build

      - name: Extract version from commit message
        id: version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"

          VERSION=$(echo "$COMMIT_MSG" | grep -oE "\[version:[0-9]+\.[0-9]+\.[0-9]+\]" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")

          if [ -z "$VERSION" ]; then
            echo "No version found in commit message!"
            exit 1
          fi

          # Remove "v" prefix if present
          CLEAN_VERSION=${VERSION#v}

          echo "version=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_FRONTEND_REPO }}
          IMAGE_TAG: ${{ steps.version.outputs.version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./frontend -f ./frontend/Dockerfile
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push backend docker image to Amazon ECR
        with:
          context: ./backend
          file: ./backend/Dockerfile
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_BACKEND_REPO }}
          IMAGE_TAG: ${{ steps.version.outputs.version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./backend -f ./backend/Dockerfile
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
