name: Node CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths: ["frontend/**", "backend/**", ".github/**"]
  pull_request:
    branches: ["main"]
    paths: ["frontend/**", "backend/**", ".github/**"]

jobs:
  check-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: npm install, lint and build for frontend
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm run build
      - name: npm install, lint and build for backend
        working-directory: backend
        run: |
          npm ci
          npm run lint
          npm run build
