name: Node CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths: ["frontend/**", "backend/**"]
  pull_request:
    branches: ["main"]
    paths: ["frontend/**", "backend/**"]

jobs:
  check-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"
      - name: npm install, lint and build for frontend
        run: |
          cd frontend 
          npm ci
          npm run lint
          npm run build --if-present
      - name: npm install, lint and build for backend
        run: |
          cd backend 
          npm ci
          npm run lint
          npm run build --if-present
