name: Node CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths: ["frontend/**", "backend/**", ".github/**"]
  pull_request:
    branches: ["main"]
    paths: ["frontend/**", "backend/**", ".github/**"]

jobs:
  check-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: npm install, lint and build for frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
      - name: npm install, lint and build for backend
        working-directory: backend
        run: |
          npm ci
          npm run build
      - name: Extract version from commit message
        id: version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"

          VERSION=$(echo "$COMMIT_MSG" | grep -oE "\[version:[0-9]+\.[0-9]+\.[0-9]+\]" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")

          if [ -z "$VERSION" ]; then
            echo "No version found in commit message!"
            exit 1
          fi

          # Remove "v" prefix if present
          CLEAN_VERSION=${VERSION#v}

          echo "version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
      - name: Print
        run: |
          echo ${{ vars.DOCKERHUB_USERNAME }}
          echo ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            abhradippaul/nodejs-frontend-devops:${{ steps.version.outputs.version }}
            abhradippaul/nodejs-frontend-devops:latest
      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            abhradippaul/nodejs-backend-devops:${{ steps.version.outputs.version }}
            abhradippaul/nodejs-backend-devops:latest
      # - name: Extract old dev version for staging
      #   id: olddev
      #   run: |
      #     OLD_DEV=$(grep -oE "newTag: [0-9]+\.[0-9]+\.[0-9]+" manifests/kustomize/overlays/dev/kustomization.yaml | head -1 | awk '{print $2}')
      #     echo "old=$OLD_DEV" >> $GITHUB_OUTPUT
      #  - name: Update image tag for staging
      #   run: |
      #     sed -i "s/newTag: [0-9]\+\.[0-9]\+\.[0-9]\+/newTag: ${{ steps.version.outputs.version }}/g" manifests/kustomize/overlays/dev/kustomization.yaml
      # - name: Update image tag for dev
      #   run: |
      #     sed -i "s/\(newTag:.*:\)[0-9]\+\.[0-9]\+\.[0-9]\+/\1${{ steps.version.outputs.version }}/" manifests/kustomize/overlays/dev/kustomization.yaml
